### ISSUE TITLE
Report rpc errors back to dapp

### ISSUE THREAD

**Issue by Necroskillz** [kukai-wallet/kukai#106]
See this issue - https://gitlab.com/tezos-domains/app/-/issues/138

Is it possible to report some error back to dapp with beacon if something like this happens (tezos node timing out/down etc.)?

**Comment by klassare** [comment]
Kukai will send back a broadcast error if it fails to inject an operation. As long as Beacon P2P transport doesn't fail, you should never get stuck in a pending state like that.
