### ISSUE TITLE
Unable to connect wallet to FA2 Bakery

### ISSUE THREAD

**Issue by Trewaters** [kukai-wallet/kukai#115]
I am unable to connect my Kukai wallet ( address tz2TTvkUkcjpHz4M8j9dq2S1HPcGu82qPki7 ) to this website (https://fa2-bakery.netlify.app/).

I select Kukai wallet as my wallet option. I see a message about pairing and waiting for permission. Then it stops and says there is a network error.

Do you have any recommendations?

**Comment by klassare** [comment]
You will need to set `preferredNetwork` to `NetworkType.FLORENCENET` in the `DAppClient` constructor. Otherwise, your Florencenet dApp will connect to Kukai's mainnet deployment, which will result in a network mismatch.

**Comment by Trewaters** [comment]
Thank you for that. It looks like that is something the fa2 website developer will need to fix.

I enjoy the wallet! Thanks for making something that works so well with Twitter Auth.
