### ISSUE TITLE
Can't connect wallet to TryShowtime with Twitter DirectAuth

### ISSUE THREAD

**Issue by WaltReu** [kukai-wallet/kukai#130]
When I try to connect my Kukai wallet to the Showtime (https://tryshowtime.com), everything seems to go fine on Kukai side, but on Showtime, I can see the wallet appear very briefly in the wallet view as red and then it disappears. However, on Kukai, if I go to the Settings, Showtime is listed in both Peers & Permissions lists.

I tried both Firefox an Chrome, tried deleting cookies etc but still won't work. Connecting Temple wallet worked fine.

edit: I tried connecting with Google DirectAuth and that seemed to work just fine. So it might be something to do with Twitter DirectAuth.

<img width="393" alt="Screen Shot 2021-06-06 at 19 31 16" src="https://user-images.githubusercontent.com/85451729/120932718-94c79500-c6ff-11eb-814e-21ac97250576.png">

**Comment by klassare** [comment]
this should have been resolved. Please reopen if still an issue.
