### ISSUE TITLE
[Unknown Token] unsendable

### ISSUE THREAD

**Issue by GlitzDreamscape** [kukai-wallet/kukai#149]
Minting nft objkts on hicetnunc.xyz & tokens sent to my wallet keep saying unknown token and don't provide the option to send/airdrop to another wallet

**Comment by metab0x** [comment]
Metadata for my token is correct on IPFS, but i have [Unknown Token] since minting 3 days ago. There is workaround to make it sendable by importing the kukai wallet using seed phrase to temple wallet. According to user reports [Unknown Token] issue in Kukai should resolve by itself after some time.

**Comment by GlitzDreamscape** [comment]
Yup  ^ω^
 under settings if you scroll to the bottom of the page there's a button
labelled "Rescan Unknown Tokens"
