### ISSUE TITLE
Error when creating new tz1

### ISSUE THREAD

**Issue by tulpenhaendler** [kukai-wallet/kukai#15]
I am getting this error when creating a new Account ( when the old Account does not have any Balance )

Id not known: proto.003-PsddFKi3.implicit.empty_implicit_contract

It would be better to show a human readable error message when the user tries to create a new account and the old account has no balance, before asking for the password

**Comment by klassare** [comment]
Thank you for reporting this issue. The error id:s have changed in the protocol updates. So we'll have modify our pipe for the error handling to become more generic. With the latest update you need to keep at least 0.257 tez in the implicit account when originating a new account.

**Comment by klassare** [comment]
This should now be solved in version 1.3.0

**Comment by roccomuso** [comment]
In a few words what this error exactly means?

**Comment by klassare** [comment]
When an implicit account (tz...) becomes empty, it is inactivated and you can't perform any operations on it. To reactivate it you need to send a transaction to that account and pay for a new burn.

**Comment by roccomuso** [comment]
what is an "implicit account"? your normal tz1... address?
What does it means pay for a new burn? like a `kind: "reveal"` operation?

**Comment by klassare** [comment]
Yes, implicit account is the tz1 address. When an implicit account receive its first transaction or after deactivation a 0.257 burn must be paid. You do this with a regular transaction with the storage limit set to at least 257.
