### ISSUE TITLE
UX: Make NFT collection searchable

### ISSUE THREAD

**Issue by nft-raider** [kukai-wallet/kukai#167]
In the old version, all token were listed on one page and I could ctrl+f search for token names to send them. Although being beautiful, the new UI does not cover this aspect and I'd like to propose a search input field. It's shown above the platform dropdowns to allow for global search. When expanding the accordion, the UI resembles the status quo.

As for the underlying search query, fetching appropriate meta data from the platforms, where applicable, would be a great addition. This info, while not present in the UI, should be taken into account for the search. For example "tags" metadata.

Bonus points for fuzzy search!

![kukai_screen](https://user-images.githubusercontent.com/89355444/133734974-34bd271c-9535-40c6-bd32-70b77fbd4b38.png)

**Comment by klassare** [comment]
Thanks for opening this issue! We have seen a lot of users request this feature in the last couple of days.

**Comment by klassare** [comment]
Closing this since Kukai now has a search feature
