### ISSUE TITLE
Error: Failed to fetch account(s). Please check your connection.

### ISSUE THREAD

**Issue by AUTISTICRETARDSFOUNDATION** [kukai-wallet/kukai#182]
Hello, 

I try to log in on my wallet and now this error keeps appearing. Any ideas?

**Comment by tezit** [comment]
When logging into an HD account, Kukai uses BCD indexing to scan for tokens in the accounts. If BCD is down then you will get this error, it usually resolves quickly. We are also working on more graceful degradation where we load the wallet but inform you that not all tokens/accounts were able to retrieve all their data.

**Comment by klassare** [comment]
Duplicated issue https://github.com/kukai-wallet/kukai/issues/72

**Comment by Quaiko** [comment]
I still dont get into my account... I dont know what to do :-( 
I downloaded the keyfile and entered my password, it only says: Error: failed to fetch accounts. Please check your connection.
