### ISSUE TITLE
Setup idiazabalnet.kukai.app to promote testing engagement within the developer ecosystem

### ISSUE THREAD

**Issue by jevonearth** [kukai-wallet/kukai#202]
**Summary**

The `idiazabalnet` testnet is now up and running. This net has many changes, including tenderbake. We must promote engagement with the Tezos development ecosystem so that we have more miles and eyes on this significant protocol update.

Please add support for `idiazabalnet` so that developers can easily develop and test against this new test network.

More info on this network is available here: https://teztnets.xyz/idiazabalnet-about
Public RPC nodes are available here: https://idiazabalnet.ecadinfra.com/

Related issues:

- Beacon: https://github.com/airgap-it/beacon-sdk/issues/294
- Taquito: https://github.com/ecadlabs/taquito/issues/1162

**Comment by klassare** [comment]
We need indexer (tzkt and bcdhub) support for idiazabalnet before we can proceed on this.

**Comment by klassare** [comment]
https://ithacanet.kukai.app
