### ISSUE TITLE
Set password fails silently (Mac standalone)

### ISSUE THREAD

**Issue by svantetobias** [kukai-wallet/kukai#21]
Version: Mac Standalone 1.3.0

"Set password" functionality fails silently, both when creating a new wallet and when importing a wallet seed. The fields are reset, I'm blocked from continuing and are stuck at the set password dialog. No error is displayed. 

If I try a weak password, an error message is displayed fine.

**Comment by svantetobias** [comment]
Ping :)

**Comment by klassare** [comment]
This must have been resolved in 1.3.1.
