### ISSUE TITLE
Web wallet not importing all address

### ISSUE THREAD

**Issue by Cryptot86** [kukai-wallet/kukai#23]
Hi 

I am trying to import my wallet using keystore file and password but not all my accounts are shown up and my delegations are also not getting displayed in web wallet. Is there anyway I can access my wallet and get my tokens back ? 

I am getting a warning message as "Something went wrong when searching after additional addresses. Try to reimport your keystore file."

**Comment by klassare** [comment]
Hi!

This is a display error that could happen if there is a connection problem to the API. So you don't have to be worried about your tokens in any way. What I would advice you to do first is to log out from the wallet. Then refresh the website (hit F5) and try to import your wallet again.

**Comment by Cryptot86** [comment]
Hi, 

Thanks for the update, still I tried to refresh and imported wallet with multiple browsers still no luck. Can I try in unix wallet ? Appreciate your help.

**Comment by Cryptot86** [comment]
I tried with web desktop wallet version "kukai-win32-ia32_1.2.3" and I can see all my account but even the latest desktop version had the same issue. Its worth looking at it this issue. - Thanks

**Comment by klassare** [comment]
We have identified a bug in the KT address import that can be triggered in some cases. A fix for this will be released as soon as possible.

**Comment by klassare** [comment]
A fix have been deployed on the web version of the wallet. Let me know if this resolved your issue.

**Comment by Cryptot86** [comment]
No Luck, still not all accounts are getting imported. Please check.

**Comment by klassare** [comment]
Ok, I will need your tz1 address in that case to find out what is going on. Could you write it here or send it in an email?

**Comment by Cryptot86** [comment]
I closed my browser and tried with new browser window and it worked fine 
1. It shows both the accounts in overview and shows all the accounts in accounts page as well 

Thanks for your help, closing the issue

**Comment by klassare** [comment]
I'm happy it's working now. Thank you for opening this issue! It helped us locate and fix a bug in the code.

**Comment by Cryptot86** [comment]
Hi, 

This issue is back again. Trying to access the web wallet using Chrome and tried windows wallet but not all the address are getting imported  

Error message : Something went wrong, try importing the keystore file again

**Comment by klassare** [comment]
Kukai use TezRPC as entrypoint to the blockchain. It's not yet fully operational after transitioning to the new protocol, but are expected to be fully operation within 4-5 hours. So in this case the integrity of the KT addresses couldn't be verified due to the current instability on the back-end. Kukai wallet require cryptographic proofs that the KT1 addresses belong to the tz1 address before showing them in the wallet. This in order to protect the user against MITM attacks. We know that this strong requirement on integrity could cause problems in cases like this, but it's a conscious choice we have made to prioritize security over availability. Thank you for your understanding.

**Comment by klassare** [comment]
The web wallet should start working as soon as TezRPC becomes stable. When we see that the web wallet is working without any problems we will release a new version of the desktop wallet.

**Comment by Cryptot86** [comment]
Great, it is working now. Thanks for the immediate response and clarifications. 

Also, is there a way, I can get private key of my wallet ?

**Comment by klassare** [comment]
No problem. Thank you for reporting the issue. =)

We don't support that directly in the wallet. The BIP39 mnemonic (15 words) is a much better (checksum + human friendly) form of backup and an established standard for Tezos wallets. You can derive the private key from the BIP39 mnemonic using some 3rd party software, but I wouldn't recommend it and it would be considered bad practice. For the regular user there's really no reason to ever deal directly with the private key.

**Comment by wenski-github** [comment]
> Ok, I will need your tz1 address in that case to find out what is going on. Could you write it here or send it in an email?

Hallo, i just got same cases. Do you can help me?

**Comment by saddge** [comment]
I am also having this issue, have logged in multiple times with seed phrase but am unable to access all of my addresses. Any and all help appreciated.
