### ISSUE TITLE
"Operation failed!" for every attempt to Send

### ISSUE THREAD

**Issue by ButteryGuitars** [kukai-wallet/kukai#24]
OS: Windows 7 x64
Wallet: Kukai 1.3

For every address I attempt to send to, I get "Operation failed!". I've seen this before infrequently and a reboot of my machine usually takes care of it. However, this time that is not the case. I cleaned out everything in %appdata%\kukai and re-imported wallet. Still same error. Unfortunately, this software doesn't appear to be writing logs anywhere for me to further investigate. %appdata%\kukai\logs is empty.

I understand there are dependencies on public Tezos API's for Kukai and possible those are having issues, but don't know what API's are in use to investigate further. I believe I saw tzscan was one and their API seems fine.

Can anyone else give me any pointers or tell me if they're having similar issues?

**Comment by klassare** [comment]
We will try to deploy a new version of the desktop wallet asap to address this. Until then, the web wallet (kukai.app) is already updated to work with the new protocol. As a temporary solution you could also follow the steps for offline signing. That way the transaction is created in the web wallet, but signed and verified remotely in your desktop wallet.

**Comment by ButteryGuitars** [comment]
Thanks for the quick response! Do you have an ETA when the desktop version will be updated? I may wait until then if it's only a day or so...

**Comment by klassare** [comment]
Could be tomorrow, but latest Saturday.
