### ISSUE TITLE
alphanet.tezrpc.me is down

### ISSUE THREAD

**Issue by vindberg** [kukai-wallet/kukai#26]
Hi, it seems that https://alphanet.tezrpc.me/ is down. Is there a way to change node?

Currently tzscan is up: https://alphanet-node.tzscan.io/chains/main/blocks/head/header

Thanks.

**Comment by klassare** [comment]
Thank you for opening this issue. We plan to implement redundancy, so that it automatically switch over to another node if one is down. I have changed node node now, so the alphanet version should work.

**Comment by vindberg** [comment]
Sounds like a good plan.

Thanks.
