### ISSUE TITLE
Transaction to multiple destinations

### ISSUE THREAD

**Issue by tezosfaust** [kukai-wallet/kukai#27]
Hello!

I tried to make a transaction to multiple destinations and got the following error: "Operation failed! Id not known: ValidationError"

Is there a way to fix this problem? If so, please tell me how.

Or is it because of the new Babylon protocoll? If so, will Kukai be updated?

**Comment by klassare** [comment]
Kukai have been updated for Babylon, but it's a very large update so there could be a few bugs. I will see if I can reproduce that error.

**Comment by tezosfaust** [comment]
thanks for your reply @klassare 

We are sending from a KT address

**Comment by klassare** [comment]
Found a bug in the new Zarith int encoding. Deploying a fix for it now., thanks for opening an issue!

**Comment by tezoskukaiuser** [comment]
Hello I had the same bug as tezosfaust. Looks like you did some update. But now another error shows up in the confirmation window: (also sending from KT address)

Operation failed!
Id not known: proto.005-PsBabyM1.gas_exhausted.operation

Please help.

**Comment by klassare** [comment]
The gas limit and fee need to be set manually right now for batch transactions. We will try to remove this manual need asap. For now, set the gas limit to 15 400 and fee to 0.0017 if you get the gas_exhausted.operation error. If you get the same error again, you can bump up the gas limit to 44 800 and fee to 0.0052.

**Comment by tezoskukaiuser** [comment]
Thanks for your answer. However it doesn't work.

1) with setting gas limit to 15 400 and fee to 0.0017 - I get the following error:
Operation failed!
Id not known: proto.005-PsBabyM1.michelson_v1.bad_contract_parameter

2) with setting gas limit to 44 800 and fee to 0.0052 - I get the following error:
Operation failed!
Id not known: proto.005-PsBabyM1.contract.balance_too_low

**Comment by klassare** [comment]
The wallet have been updated now to use better default values for batch transactions. The manager address (tz1) will pay the transactions fee when you send batch transactions from a KT address. So, make sure you have enough balance on the tz address.

**Comment by tezoskukaiuser** [comment]
Perfekt. It worked. There is still a max operation size, so I split payments (approx 150) in two different transactions. I really appreciate your help. Thanks a lot!

**Comment by roccomuso** [comment]
what's the ideal gas value when sending a normal tx?
Like half the max limit?

**Comment by klassare** [comment]
@roccomuso The ideal gas value should be determined by simulating ([preapply](http://doc.tzalpha.net/api/rpc.html#post-block-id-helpers-preapply-operations) or [run_operation](http://doc.tzalpha.net/api/rpc.html#post-block-id-helpers-scripts-run-operation)) the transaction. To simplify it, the Kukai wallet is using the [following ](https://github.com/kukai-wallet/kukai/blob/web/src/app/components/send/send.component.ts#L23) default values based on 4 common situations.
