### ISSUE TITLE
Token thumbnails not showing in wallet for custom FA2 contract

### ISSUE THREAD

**Issue by hanexperience** [kukai-wallet/kukai#272]
Hi there,

We have a custom FA2 running on mainnet at https://tzkt.io/KT1SRFbwhvfkXoRGqiDFVVsf5GTp16wGgtCa

When we did our testing on hangzhounet everything worked well, however after the migration to mainnet our thumbnails are not showing.

![image](https://user-images.githubusercontent.com/96176996/151286059-2071ef06-6b62-4924-b281-4d8596a3b52f.png)

Do we need to get whitelisted?

**Comment by klassare** [comment]
You can open a PR to add an alias and whitelist the contract. You can check old PR's for what we expect in that PR.

**Comment by klassare** [comment]
resolved
