### ISSUE TITLE
Error resolving tezos domain names when trying to send a token

### ISSUE THREAD

**Issue by clauswilke** [kukai-wallet/kukai#277]
In the last few days, I haven't been able to send tokens to Tezos domains. When I enter the domain name, I get "TYPEERROR: CANNOT READ PROPERTIES OF UNDEFINED (READING 'DECODE')". This worked just fine a week ago. The domain is not expired.

<img width="419" alt="Screen Shot 2022-01-29 at 11 39 54 AM" src="https://user-images.githubusercontent.com/4210929/151671498-ea0fface-d267-4ec6-bc61-c9c3bd5d2c7d.png">

**Comment by klassare** [comment]
Resolved in https://github.com/kukai-wallet/kukai/commit/19ba5876a59ce4e509edc22bfcc5ba3191cd0095

**Comment by clauswilke** [comment]
Thanks for fixing this so quickly!
