### ISSUE TITLE
Kukai wallet address is showing different with the twitter login.

### ISSUE THREAD

**Issue by cryptoelixir07** [kukai-wallet/kukai#293]
I had an kukai account create with the my twitter handle / twitter account. I had no issues until a day before when I was trying to buy some NFT and it gave me a reconnect error. I restarted my mobile, didn't help ! 

So I had to logout from the kukai app and login with my twitter account and it logme in .. However I see a different wallet address. 
I am sure I have not had/changed my twitter account and I have only one account.

Worried that I lost my wallet, I checked in the Txkt.io to see the previous address still there and have all my tokens, NFT, Tez it's there. So not sure why I got in this weird situation

Appreciate any help on this :)

My wallet address that I lost : tz1eNmfm1V2qW5codUZZcUFFj7XyvrpK3ev3

Thanks
Cryptoelixir

**Comment by klassare** [comment]
That address does not belong to a twitter account. You will need to import your wallet from seed words or keystore file, see: https://docs.kukai.app/learn-kukai/import-wallet
