### ISSUE TITLE
Kukai <> Swapzone Integration

### ISSUE THREAD

**Issue by SZ-olya** [kukai-wallet/kukai#296]
Hello Kukai Team,

I'm Olya, bizdev at Swapzone aggregator of crypto exchanges. 
 
I  would like to know whether there's a possibility for us as an aggregator of exchanges offering rates, 600+ currencies and deals from 20+ exchange providers to integrate with Kukai Wallet. We believe it would enhance the functionality of the wallet since the users would be able to swap our 600+ crypto coins and tokens at the best rate without leaving the app. We do have an API for that and we'd be beyond happy to elevate the discussion further.  

My mail is olya@swapzone.io, but TG is better for contacting: SZ_olya

**Comment by klassare** [comment]
message received
