### ISSUE TITLE
Cant move my funds from KT

### ISSUE THREAD

**Issue by AndyShores** [kukai-wallet/kukai#30]
"An operation tried to spend more tokens than the contract has" - the message i get when i try to move 1 tz from my KT contract to any address with any option of fee\gas\etc. having 3k+ tokens on actual KT balance. The same message i get trying to redelegate.

Please provide help with this. Funds are stuck.

**Comment by klassare** [comment]
Make sure you have enough funds available on the manager address (tz1) to pay for the transaction fee.

**Comment by AndyShores** [comment]
> Make sure you have enough funds available on the manager address (tz1) to pay for the transaction fee.

Thanks a lot! That helped! Didnt know the transaction fee is spent from the tz1 address/

**Comment by klassare** [comment]
After the Babylon update the tz1 address pays for all fees. We will update this error message to give a more accurate description of what went wrong. Thank you for reporting this issue!
