### ISSUE TITLE
codecov in deps

### ISSUE THREAD

**Issue by martinpospech** [kukai-wallet/kukai#32]
Is it needed for the production build?

**Comment by klassare** [comment]
Thanks for pointing this out. It should be a dev dep instead if it's needed. Will do an overhaul of all dependencies.

**Comment by klassare** [comment]
Have been [addressed ](https://github.com/kukai-wallet/kukai/commit/db6f5aa4baf2f6e462ffb02681138c205769a00f) for the web deployment.
