### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by littlemadhatter** [kukai-wallet/kukai#34]
Ability to hide unused/no-tezos kt1 address.
While creating a kt1 address, I messed up and i have 2 unused kt1 address i can't use because it didn't broadcast correctly (my fault) and now they just sit there unused and it messes with my OCD and I think it will be a good way for cleaning up the address page for me but for other people too.

**Comment by klassare** [comment]
Will look into this. It shouldn't add a KT1 address if the origination isn't broadcasted successfully. In the short term you can try to logout and then import the wallet again. This will clear everything and reload all your addresses. A checkbox to hide all addresses with low balance sounds like a very good suggestion.

**Comment by littlemadhatter** [comment]
Re importing did remove the address, thank you.
But yes, I do think a checkbox to hide address with no balance could be a ok idea.
