### ISSUE TITLE
operation failed! 

### ISSUE THREAD

**Issue by lifelongperfection** [kukai-wallet/kukai#35]
Hello! I try to transfer my token funds to another wallet, but the following error comes out: "A script or one of its callee took more time than the operation said it should". Tell me, please, what am I doing wrong? Thank you!

**Comment by klassare** [comment]
It means that the gas limit was set too low. What gas limit did you use? Did you try to send from a tz address to another tz address?

**Comment by lifelongperfection** [comment]
Everything is ok now, thanks!
The gas limit was low.
