### ISSUE TITLE
Desktop app no longer works. Web app still works

### ISSUE THREAD

**Issue by nik-g-second** [kukai-wallet/kukai#40]
As of a few days ago, the Desktop app no longer works on Mac OS. The app starts, but fails to retrieve the updated account balances.

However, the web app is updating the balances correctly.

**Comment by klassare** [comment]
The desktop wallet was never updated for Babylon. Due to limited resources at that time, the priority became to keep the web wallet operational. After Kukai 2.0 have been launched we will revise what platforms to support.
