### ISSUE TITLE
Import into Another Wallet

### ISSUE THREAD

**Issue by nik-g-second** [kukai-wallet/kukai#41]
I was recently playing with another wallet (Galleon) and tried to import my account (15 word seed and passphrase). It was originally created with Kukai. That didn't work. Does Kukai use a proprietary seed format, which is not used in other wallets? How can I reveal the private key, so I can try importing it into another wallet?

**Comment by klassare** [comment]
Kukai uses the same seed format (BIP-39) as Galleon and many other wallets. Just make sure you leave the passphrase empty.

**Comment by nik-g-second** [comment]
Ah, so the password must be empty! I tried without password and that didn't work. 

It worked this time, thanks!

However, I have 2 accounts in Kukai (in addition to the identity). Once I imported in Galleon, I can only see one of the accounts. Do you have any idea why or is it a bug in Galleon?

**Comment by klassare** [comment]
I'm not sure if it's a bug in Galleon or if they have made another design decision. Can for example be that they decided to not display KT accounts originated after Babylon.

**Comment by shaun19826** [comment]
@nik-g-second Hello, Are you still having issues not seeing both accounts when you restore your wallet on the galleon wallet ?
