### ISSUE TITLE
Kukai Ghostnet not working

### ISSUE THREAD

**Issue by nicolaswagnerdev** [kukai-wallet/kukai#411]
Hello, 
I am using Kukai ghostnet for an app I'm developping and it doesn't seem to work anymore. I found in the logs that kukai ghostnet calls a network from Infura which has been deprecated the 05/10/2022 =>
https://blog.infura.io/post/deprecation-timeline-for-rinkeby-ropsten-and-kovan-testnets

```
Access to fetch at 'https://ropsten.infura.io/v3/b8cdb0e4cff24599a286bf8e87ff1c96' from origin 'https://ghostnet.kukai.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
ropsten.infura.io/v3/b8cdb0e4cff24599a286bf8e87ff1c96:1          Failed to load resource: net::ERR_FAILED
```

I have several questions : 
- Is my problem linked with Infura Ropsten deprecation? I don't see any mention of Tezos and it seems to host only Ethereum testnets.
- If so, is there any workaround possible? Like alternative testnets?

If you have any useful info I'm happy to hear it :)

**Comment by klassare** [comment]
Related to https://github.com/orgs/Web3Auth/discussions/685

We will modify the initialization of `TorusSdk` on Kukai's end to resolve this.

**Comment by klassare** [comment]
This issue should be resolved now

**Comment by nicolaswagnerdev** [comment]
It seems to be solved on my end, thanks 👍
