### ISSUE TITLE
misleading error when underlying infra unreachable

### ISSUE THREAD

**Issue by martinpospech** [kukai-wallet/kukai#50]
The wallet gives a "wrong password" error when trying to restore a wallet and nodes are not reached. Unclear if this only happens when 3rd party resources are blocked or also when the connection is just unreliable, as I didn't investigate further.

**Comment by klassare** [comment]
Thanks for pointing this out. This error message will be shown if the password is wrong or if the account scanning (dependency on indexer API) fails in some way. Will fix this bug in the next release.

**Comment by klassare** [comment]
Have been fixed in #52
