### ISSUE TITLE
Cannot sign in to wallet using twitter.

### ISSUE THREAD

**Issue by pruzzz** [kukai-wallet/kukai#503]
My transactions are not being authorised. Now I see I also cannot sign into my wallet using Twitter. I expect these issues are connected and Twitter have done something to their API. This problem exists on both my wallets that use my Twitter to sign-in.

Thanks!

**Comment by klassare** [comment]
Thank you for reporting this issue. Some of our users are experiencing similar problems. There are currently some intermittent network errors affecting social login (not only Twitter). We are trying to resolve this with our partners.

**Comment by klassare** [comment]
Can you double check that the error you are reporting is related by trying to login with for example Google on the same device?

**Comment by pruzzz** [comment]
Yes, the problem is also there with google, ie the ꜩ loading circle appears, hangs, then disappears without sign-in. Assuming this issue also causes authentication problems for any kind of transaction using kukai wallet ?

Thanks very much for your swift reply.

**Comment by klassare** [comment]
Ok, I can fully reproduce this issue. Doesn't seem to be intermittent.

**Comment by klassare** [comment]
Fix have now been deployed in production. So, it should work as normal again. Thank you for bringing this issue to our attention!

**Comment by pruzzz** [comment]
Yes, I noticed it was working again. Thanks for the quick fix on this. Back up and running :)
