### ISSUE TITLE
Can't sign in to wallet

### ISSUE THREAD

**Issue by keremozturkben** [kukai-wallet/kukai#504]
Hello. I can't login to my wallet. I was using with with google account login. I've checked my google account, it seems safe. I've logged out from it and logged in again. I tried to reach wallet again. I just can see Tezos logo for a while, then nothing happens. Is this could be a maintainment issue or what else ?

**Comment by klassare** [comment]
Hi, we have now deployed a fix, so should work as normal again. Sorry for the inconvenience...
