### ISSUE TITLE
Add money every 3 days to list of bakers

### ISSUE THREAD

**Issue by songproducer** [kukai-wallet/kukai#544]
Hi! Can my baker please be added to the list? I recommend people to use kukai and it's a bit cumbersome to have them add my baker manually.

Here's my bakers address:

tz1NEKxGEHsFufk87CVZcrqWu8o22qh46GK6

**Comment by klassare** [comment]
Hi!
Your baker will show up in the list for users that has a tez balance that exceeds 100 tez (minDelegation). If you want your baker to show up in the list for all users, you need to change that requirement.

<img width="528" alt="Skärmavbild 2024-02-28 kl  12 23 40" src="https://github.com/kukai-wallet/kukai/assets/31806893/5c02eac9-9a33-4f47-8292-f20417fbcd37">

https://api.baking-bad.org/v2/bakers
