### ISSUE TITLE
Cannot login to wallet

### ISSUE THREAD

**Issue by veiderlord** [kukai-wallet/kukai#553]
Cannot login to account. I've tried to use both google and email method. The only thing I get is "Failed to fetch" message.
my address: tz2MKwzYxAhfCty1263j1i4VKvoNbNu8sryK

**Comment by klassare** [comment]
What browser and device are you using? Is this on a home network or what kind of network are you on?

**Comment by veiderlord** [comment]
Nice idea, it worked. I just turned on the VPN. Thanks!
