### ISSUE TITLE
Permission matrix cleanup

### ISSUE THREAD

**Issue by xpht** [kukai-wallet/kukai#606]
Some whitelisted domains at 
https://github.com/kukai-wallet/kukai/blob/production/src/app/components/views/embedded/embedded.component.ts
do not exist anymore and can be taken over by 3rd party (resulting in domain or subdomain takeover, with ability to embed kukai components)

It may be good idea to clean them out:

origins: ['https://playwithbrio.com', 'https://www.playwithbrio.com', 'https://production.playwithbrio.com'],
origins: ['https://minterpop.com', '*.minterpop.com'],
origins: ['https://interpopcomics.com', 'https://www.interpopcomics.com'],
origins: ['https://human-machine.io'],
origins: ['https://block-space.app'],
origins: ['https://studioexception.eu'],
origins: ['https://play.emergentstcg.com'],
origins: ['https://convincethebouncer.com'],

Example:
![Screenshot 2024-11-28 052040](https://github.com/user-attachments/assets/8fc4f097-33eb-4f15-8b58-43ca6bd5547d)

**Comment by klassare** [comment]
Thank you for highlighting this risk!
