### ISSUE TITLE
Error: Failed to fetch account(s). Please check your connection.

### ISSUE THREAD

**Issue by cmoroney** [kukai-wallet/kukai#85]
Hello!

I have been signed in to my Kukai wallet on this computer for months without issue. The lastest Tezos Twitter promotion required signing into Kuaki using Twitter, so I needed to sign out. After I did that I tried to sign into my other wallet using the keystore file and I received the error:

 "Error: Failed to fetch account(s). Please check your connection."

I even tried going in and downloading a new keystore file with my mneumonic phrase and address to no avail. Anything else I should try to get into my wallet?

**Comment by klassare** [comment]
Hi!

There's currently a certificate issue with one of the API's Kukai is using. We expect that this problem will be resolved in a couple of hours. Sorry for the inconvenience this may cause.

**Comment by ya7gisa0** [comment]
I logged out today and tried to log into my wallet using the keystore file and the password. I got the same error...

**Comment by ya7gisa0** [comment]
I can import my wallet in an incognito window. That's good to know at least.

**Comment by klassare** [comment]
The API is much more stable now. We also fixed a bug that could caused this error message to be displayed when it shouldn't.
