### ISSUE TITLE
fa2 token not loading.

### ISSUE THREAD

**Issue by sebuhbitcoin** [kukai-wallet/kukai#98]
![image](https://user-images.githubusercontent.com/5566620/117890097-645c1a80-b269-11eb-89fc-e23999c0a394.png)

The send button is missing on this token.

its a twitter based wallet.

its happening to everyone that made the wallet with twitter auth. not sure about the other 2 auths.

ame
[Unknown token]

Symbol

Description
—

Contract Address
KT1KdYiNTTByYQp7R3gxjc9K5rhQ2qtYdDTR

**Comment by klassare** [comment]
Can't find any token metadata for that token. It's just empty when I check at: https://better-call.dev/mainnet/KT1KdYiNTTByYQp7R3gxjc9K5rhQ2qtYdDTR/storage

**Comment by metab0x** [comment]
Hi, I'm having the same issue with token minted at hicetnunc.xyz.  Did you resolve it?
